// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx-f-UomB4VEZagy6wREAoCpeS5mLbppU',
    appId: '1:689432359898:web:1d526d534403dfcc1246e3',
    messagingSenderId: '689432359898',
    projectId: 'oguz-news-app',
    authDomain: 'oguz-news-app.firebaseapp.com',
    storageBucket: 'oguz-news-app.firebasestorage.app',
    measurementId: 'G-07VQ4JFBRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArQzNOxvy0HZiWlELXDYu_AyRr8HW0Xs',
    appId: '1:689432359898:android:bbd92dad7c0ca9131246e3',
    messagingSenderId: '689432359898',
    projectId: 'oguz-news-app',
    storageBucket: 'oguz-news-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6QpPQ24fs0ao47p45NPTDZtbz17y-5k',
    appId: '1:689432359898:ios:2f05d250c53168561246e3',
    messagingSenderId: '689432359898',
    projectId: 'oguz-news-app',
    storageBucket: 'oguz-news-app.firebasestorage.app',
    iosBundleId: 'com.example.newsAppOguz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx6QpPQ24fs0ao47p45NPTDZtbz17y-5k',
    appId: '1:689432359898:ios:2f05d250c53168561246e3',
    messagingSenderId: '689432359898',
    projectId: 'oguz-news-app',
    storageBucket: 'oguz-news-app.firebasestorage.app',
    iosBundleId: 'com.example.newsAppOguz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx-f-UomB4VEZagy6wREAoCpeS5mLbppU',
    appId: '1:689432359898:web:9b52795955537cfd1246e3',
    messagingSenderId: '689432359898',
    projectId: 'oguz-news-app',
    authDomain: 'oguz-news-app.firebaseapp.com',
    storageBucket: 'oguz-news-app.firebasestorage.app',
    measurementId: 'G-ZDR8S00ZBY',
  );
}
